Resources:
  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    DependsOn: ApiGatewayMethodAny
    Properties:
      StageName: '${self:provider.stage}'
      DeploymentId:
        Ref: __deployment__
      RestApiId:
        Ref: ApiGatewayRestApi
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
  ApiGatewayPublicBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DependsOn: ApiGatewayStage
    Properties:
      BasePath: '${self:app}-${self:service}'
      DomainName: '${self:provider.stage}-api.syndpe.com'
      RestApiId:
        Ref: ApiGatewayRestApi
      Stage:
        Ref: ApiGatewayStage
