Resources:
  grower-contracts:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:ESHttp*'
            Resource: >-
              arn:aws:es:${self:provider.region}:${self:custom.accounts.${self:provider.stage}}:domain/${self:custom.es.grower-contracts.domain}/*
      DomainName: '${self:custom.es.grower-contracts.domain}'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: '${self:custom.es.grower-contracts.volumes.${self:provider.stage}}'
        VolumeType: gp2
      ElasticsearchClusterConfig:
        InstanceCount: '${self:custom.es.grower-contracts.instance_count}'
        InstanceType: >-
          ${self:custom.es.grower-contracts.instance_size.${self:provider.stage}}
      ElasticsearchVersion: '${self:custom.es.grower-contracts.version}'
  seed-stewardship:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:ESHttp*'
            Resource: >-
              arn:aws:es:${self:provider.region}:${self:custom.accounts.${self:provider.stage}}:domain/${self:custom.es.seed-stewardship.domain}/*
      DomainName: '${self:custom.es.seed-stewardship.domain}'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: '${self:custom.es.seed-stewardship.volumes.${self:provider.stage}}'
        VolumeType: gp2
      ElasticsearchClusterConfig:
        InstanceCount: '${self:custom.es.seed-stewardship.instance_count}'
        InstanceType: >-
          ${self:custom.es.seed-stewardship.instance_size.${self:provider.stage}}
      ElasticsearchVersion: '${self:custom.es.seed-stewardship.version}'
  grain-ops:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:ESHttp*'
            Resource: >-
              arn:aws:es:${self:provider.region}:${self:custom.accounts.${self:provider.stage}}:domain/${self:custom.es.grain-ops.domain}/*
      DomainName: '${self:custom.es.grain-ops.domain}'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: '${self:custom.es.grain-ops.volumes.${self:provider.stage}}'
        VolumeType: gp2
      ElasticsearchClusterConfig:
        InstanceCount: '${self:custom.es.grain-ops.instance_count}'
        InstanceType: '${self:custom.es.grain-ops.instance_size.${self:provider.stage}}'
      ElasticsearchVersion: '${self:custom.es.grain-ops.version}'
Outputs:
  Elasticsearchgrower-contractsDomain:
    Value:
      Ref: grower-contracts
  Elasticsearchgrower-contractsArn:
    Value: null
  Elasticsearchgrower-contractsEndpoint:
    Value: null
  Elasticsearchseed-stewardshipDomain:
    Value:
      Ref: seed-stewardship
  Elasticsearchseed-stewardshipArn:
    Value: null
  Elasticsearchseed-stewardshipEndpoint:
    Value: null
  Elasticsearchgrain-opsDomain:
    Value:
      Ref: grain-ops
  Elasticsearchgrain-opsArn:
    Value: null
  Elasticsearchgrain-opsEndpoint:
    Value: null
