Resources:
  grower-tests:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      AllocatedStorage: 100
      AvailabilityZone: '${self:provider.region}a'
      PubliclyAccessible: true
      StorageType: gp2
      DBInstanceClass: '${self:custom.db_instance_size.${self:provider.stage}}'
      DBInstanceIdentifier: '${self:provider.stackTags.name}'
      DBName: grower-tests
      StorageEncrypted: true
      VPCSecurityGroups:
        - Ref: RDSSecurityGroup
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      MasterUsername: root
      MasterUserPassword: root_password
      Engine: mysql
      EngineVersion: 5.7.26
    DeletionPolicy: Snapshot
