Resources:
  GrowerContractsNotificationsTopic:
    ContentBasedDeduplication: false
    DisplayName: GrowerContractsNotifications
    TopicName: '${self:provider.stage}-GrowerContractsNotifications'
  GrowerContractsNotificationsSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: sqs
      Endpoint:
        'Fn::GetAtt':
          - GrowerContractsQueue
          - Arn
      Region: '${self:provider.region}'
      TopicArn: >-
        arn:aws:sns:${self:provider.region}:${self:custom.accounts.${self:provider.stage}}:${self:provider.stage}-GrowerContractsNotifications
      RawMessageDelivery: true
      FilterPolicy:
        docusign_event:
          - callback
