environment:
  APP_NAME: '${self:app}-${self:service}'
  SERVICE: '${self:app}-${self:service}'
  STACK: '${self:provider.stackTags.name}'
  STAGE: '${self:provider.stage}'
  REGION: '${self:provider.region}'
  NEO4J_HOST: '${self:custom.neo4j_config.${self:provider.stage}.host}'
  NEO4J_USER: '${self:custom.neo4j_config.${self:provider.stage}.user}'
  NEO4J_PASSWORD: '${self:custom.neo4j_config.${self:provider.stage}.password}'
  NEO4J_ENCRYPTED: false
  DB_NAME: grower-tests
  DB_APP_USER: grower-tests
  DB_HOST: 127.0.0.1
  DB_MASTER_USER: root
  DB_MASTER_PASS: root_password
  DB_URI: 'mysql://root:root_password@127.0.0.1:3306/grower-tests'
  POSTGRES_DB_NAME: grower-tests
  DYNAMO_SERVERLESS_TEST: '${self:provider.stackTags.name}-serverless-test'
  ELASTICSEARCH_grower_contracts_INDEX: enogen
  ELASTICSEARCH_grower_contracts_TYPE: contract
  ELASTICSEARCH_GROWER_CONTRACTS_DOMAIN: grower-contracts
  ELASTICSEARCH_seed_stewardship_INDEX: enogen
  ELASTICSEARCH_seed_stewardship_TYPE: steward
  ELASTICSEARCH_SEED_STEWARDSHIP_DOMAIN: seed-stewardship
  ELASTICSEARCH_grain_ops_INDEX: grain
  ELASTICSEARCH_grain_ops_TYPE: ops
  ELASTICSEARCH_GRAIN_OPS_DOMAIN: grain-ops
authorizer:
  arn: false
  name: false
  type: false
  identitySource: false
  resultTtlInSeconds: false
cors:
  origin: '*'
  allowCredentials: false
  headers:
    - Content-Type
    - x-master-key
    - x-api-key
    - x-user-token
